### ISSUE TITLE
Error importing pypsg

### ISSUE THREAD

**Issue by LordFurno** [tedjohnson12/pypsg#32]
When I import pyspsg I get the following error:
Exception has occurred: SyntaxError
invalid syntax (request.py, line 210)

**Comment by tedjohnson12** [comment]
Hi @LordFurno! Thanks for submitting this issue. It seems I forgot to update the python version requirements when I put in that `match` statement. I'll fix this in the next release. For now you should upgrade your python environment to use `python>=3.10`. Hope that helps!

**Comment by LordFurno** [comment]
Thank you for the clarification!

**Comment by LordFurno** [comment]
I updated my python version, to 3.10, and now I get a different issue 

``` 
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-3-fd95ada1908a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import pypsg

8 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1861                     if errno_num != 0:
   1862                         err_msg = os.strerror(errno_num)
-> 1863                     raise child_exception_type(errno_num, err_msg, err_filename)
   1864                 raise child_exception_type(err_msg)
   1865 

FileNotFoundError: [Errno 2] No such file or directory: 'docker'

```

**Comment by tedjohnson12** [comment]
Could you include the full error output? It might be difficult to get IPython to output that so you could go to the terminal and type `python -c "import pypsg"`. Did you install the latest release via pip?

**Comment by LordFurno** [comment]
I installed pypsg with the command `pip install pypsg`

This is the full error output:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\LordFurno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pypsg\__init__.py", line 6, in <module>
    from .request import APICall, PSGResponse
  File "C:\Users\LordFurno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pypsg\request.py", line 19, in <module>
    docker.set_url_and_run()
  File "C:\Users\LordFurno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pypsg\docker.py", line 175, in set_url_and_run
    if is_psg_installed():
       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\LordFurno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pypsg\docker.py", line 47, in is_psg_installed
    containers_info = _get_containers_json()
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LordFurno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pypsg\docker.py", line 14, in _get_containers_json
    raw_output = subprocess.check_output(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

**Comment by tedjohnson12** [comment]
Can you try installing from the branch `tedjohnson12/issue32`? I've made some changes there that are Windows-specific. I have never run any of this on a Windows machine before so there are some issues that I have not yet encountered. You can
```
git clone https://github.com/tedjohnson12/pypsg.git
cd pypsg
git checkout tedjohnson12/issue32
pip install -e .
python3 -c "import pypsg"
```
I believe this should import correctly, but there might be other errors down the line. Specifically it seems like Windows does not like waiting for PSG API calls to finish, which causes a backup that PSG does not like.

**Comment by LordFurno** [comment]
Thank you this works well. Just a quick question, what are possible parameters for output types when calling pypsg.APICall()? Can you get it to return transmittance data?

**Comment by tedjohnson12** [comment]
Right now only `rad`, `cfg`, `noi`, `lyr`, `set`, and `upd` are fully supported, while `all` is semi-supported (will only parse the rad, noi, lyr, and cfg portions of the reply). `trn` outputs are not that complicated and I could include support for it in the next release. If you are up for the challenge you are more than welcome to add the functionality yourself. A `PyTrn` class would probably be very similar to `pypsg.rad.PyRad` (i.e. inherit from Astropy `QTable`) and not that difficult to implement.

**Comment by tedjohnson12** [comment]
It turns out that its super easy to implement. Try doing a `git pull` on that same issue branch and set the output type to `trn`. You can do something like
```
caller = APICall(...)
response = caller()
trn = response.trn
wl = trn.wl
o3 = trn['O3']
plt.plot(wl,o3)
```

**Comment by LordFurno** [comment]
When I git pull the updated branch I get the following error:
```
Exception has occurred: IndexError
list index out of range
  File "C:\Users\LordFurno\Downloads\getting_pypsg_toWork\pypsg\pypsg\trn\trn.py", line 28, in _get_metadata
    re.findall(r'Spectral unit:.+\[(.+)\]\n',header)[0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\LordFurno\Downloads\getting_pypsg_toWork\pypsg\pypsg\trn\trn.py", line 46, in from_bytes
    metadata = cls._get_metadata('\n'.join(header))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LordFurno\Downloads\getting_pypsg_toWork\pypsg\pypsg\request.py", line 340, in __call__
    return PSGResponse(**{self._type:returntype.from_bytes(reply.content)})
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LordFurno\Downloads\getting_pypsg_toWork\pypsg\test2.py", line 16, in <module>
    response = caller()
               ^^^^^^^^
IndexError: list index out of range
```
When running the following code:
```
import pypsg


cfg = pypsg.cfg.PyConfig(
    target=pypsg.cfg.Target(object='Exoplanet',name='Proxima Cen b')
    )



caller = pypsg.APICall(
        cfg=cfg,
        output_type='trn',
    )
response = caller()
trn = response.trn
```

**Comment by tedjohnson12** [comment]
This happens because there is no atmospheric information for PSG/PUMAS to work with, so the API call returns an empty string `''`. Try downloading a config from the PSG GUI and reading it into python with `cfg = pypsg.cfg.PyConfig.from_file('path/to/config')`

**Comment by LordFurno** [comment]
Thank you for your help, I appreciate it greatly. Just one last question, does this package require a PSG API key to make more calls?
